server:
    port: 8080
spring:
    application:
        name: user-service-hex
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:database_users;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: user_nisum
        password: admin123
        hikari:
            auto-commit: true
            minimum-idle: 5
            maximum-pool-size: 10
            idle-timeout: 30000
            max-lifetime: 1800000
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
    flyway:
        enabled: true
        locations: classpath:db/migration/test


config:
    jwtExpiration: 99990000
    secretKeyJWT: Wert45hZc2lnc1Rva2VuRm9ySldUSE1TMTIzNDU2NzxcQ3=2

    regex:
        email: "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Za-z]{2,}$"
        password: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"


management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,env


springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html

logging:
    level:
        root: INFO
        org.springframework: INFO
        com.example.registration: DEBUG